gsp:
    terminalId:         SOMATECH002
    partnerCentralId:   0090029

iso:
    server:
        listener:
            ip:     119.82.224.226
            port:   8085
        dial:
            ip:     localhost
            port:   8085
            # ip:     103.30.85.35
            # port:   40060

mti:
    netman:
        request:    2800
        response:   2810
    inquiry:
        request:    2100
        response:   2110
    payment:
        request:    2200
        response:   2210
    reversal:
        request:    2400
        response:   2410
        repeat:
            request:    2401
            response:   2411

            
# appname: test
    
# db:
#     name:     aripaja
#     user:     adaapa
#     password: kamukemanaaja
#     port:     1234

# contacts:
# - name: i test
#   email: test@test.com